2024-07-10 08:11:45.966 [info] Experiment 'pythonCreateEnvOnPipInstall' is active
2024-07-10 08:11:45.966 [info] Experiment 'pythonRecommendTensorboardExt' is active
2024-07-10 08:11:45.966 [info] Experiment 'pythonTerminalEnvVarActivation' is active
2024-07-10 08:11:45.966 [info] Experiment 'pythonTestAdapter' is active
2024-07-10 08:11:45.966 [error] Reading directory to watch failed [Error: ENOENT: no such file or directory, scandir '/home/ndao/DB_Provisionning/.pixi/envs'
	at Object.readdirSync (node:fs:1517:26)
	at /home/ndao/.vscode-server/extensions/ms-python.python-2024.10.0-linux-x64/out/client/extension.js:2:574598
	at /home/ndao/.vscode-server/extensions/ms-python.python-2024.10.0-linux-x64/out/client/extension.js:2:574789
	at Array.map (<anonymous>)
	at d.initWatchers (/home/ndao/.vscode-server/extensions/ms-python.python-2024.10.0-linux-x64/out/client/extension.js:2:574507)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async d.ensureWatchersReady (/home/ndao/.vscode-server/extensions/ms-python.python-2024.10.0-linux-x64/out/client/extension.js:2:536827)] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/home/ndao/DB_Provisionning/.pixi/envs'
}
2024-07-10 08:11:45.966 [error] Dir "/home/ndao/DB_Provisionning/.pixi/envs" is not watchable (directory does not exist)
2024-07-10 08:11:45.966 [info] Default formatter is set to null for workspace /home/ndao/DB_Provisionning
2024-07-10 08:11:45.966 [info] Python interpreter path: /bin/python3
2024-07-10 08:11:46.122 [info] > pyenv which python
2024-07-10 08:11:46.122 [info] cwd: .
2024-07-10 08:11:46.922 [info] > pixi --version
2024-07-10 08:11:46.925 [error] [Error: spawn pixi ENOENT
	at ChildProcess._handle.onexit (node:internal/child_process:286:19)
	at onErrorNT (node:internal/child_process:484:16)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn pixi',
  path: 'pixi',
  spawnargs: [ '--version' ]
}
2024-07-10 08:11:46.925 [warning] could not find a pixi interpreter for the interpreter at /bin/python3
2024-07-10 08:11:49.004 [info] Starting Pylance language server.
