2024-05-23 08:29:14.232 [info] Experiment 'pythonCreateEnvOnPipInstall' is active
2024-05-23 08:29:14.232 [info] Experiment 'pythonRecommendTensorboardExt' is active
2024-05-23 08:29:14.232 [info] Experiment 'pythonTerminalEnvVarActivation' is active
2024-05-23 08:29:14.232 [info] Experiment 'pythonTestAdapter' is active
2024-05-23 08:29:14.232 [info] Default formatter is set to null for workspace /home/ndao
2024-05-23 08:29:14.232 [info] > conda info --json
2024-05-23 08:29:14.232 [info] > hatch env show --json
2024-05-23 08:29:14.232 [info] cwd: .
2024-05-23 08:29:14.232 [info] Found: /bin/python3 --> /bin/python3.8
2024-05-23 08:29:14.284 [info] Found: /bin/python3.8 --> /bin/python3.8
2024-05-23 08:29:14.586 [info] Found: /usr/bin/python3 --> /usr/bin/python3.8
2024-05-23 08:29:14.586 [info] Found: /usr/bin/python3.8 --> /usr/bin/python3.8
2024-05-23 08:29:14.620 [info] > C:\Users\Admin\AppData\Local\Programs\Python\Python312\python.exe -I ./.vscode-server/extensions/ms-python.python-2024.6.0/python_files/get_output_via_markers.py ./.vscode-server/extensions/ms-python.python-2024.6.0/python_files/interpreterInfo.py
2024-05-23 08:29:14.653 [error] [Error: Command failed: C:\Users\Admin\AppData\Local\Programs\Python\Python312\python.exe -I /home/ndao/.vscode-server/extensions/ms-python.python-2024.6.0/python_files/get_output_via_markers.py /home/ndao/.vscode-server/extensions/ms-python.python-2024.6.0/python_files/interpreterInfo.py
/bin/sh: 1: C:UsersAdminAppDataLocalProgramsPythonPython312python.exe: not found

	at ChildProcess.exithandler (node:child_process:422:12)
	at ChildProcess.emit (node:events:529:35)
	at maybeClose (node:internal/child_process:1098:16)
	at Socket.<anonymous> (node:internal/child_process:450:11)
	at Socket.emit (node:events:517:28)
	at Pipe.<anonymous> (node:net:350:12)] {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\python.exe -I /home/ndao/.vscode-server/extensions/ms-python.python-2024.6.0/python_files/get_output_via_markers.py /home/ndao/.vscode-server/extensions/ms-python.python-2024.6.0/python_files/interpreterInfo.py'
}
2024-05-23 08:29:14.885 [info] > /bin/python3 -I ./.vscode-server/extensions/ms-python.python-2024.6.0/python_files/get_output_via_markers.py ./.vscode-server/extensions/ms-python.python-2024.6.0/python_files/interpreterInfo.py
2024-05-23 08:29:14.910 [info] > /usr/bin/python3 -I ./.vscode-server/extensions/ms-python.python-2024.6.0/python_files/get_output_via_markers.py ./.vscode-server/extensions/ms-python.python-2024.6.0/python_files/interpreterInfo.py
2024-05-23 08:29:16.743 [info] > C:\Users\Admin\AppData\Local\Programs\Python\Python312\python.exe -I ./.vscode-server/extensions/ms-python.python-2024.6.0/python_files/get_output_via_markers.py ./.vscode-server/extensions/ms-python.python-2024.6.0/python_files/interpreterInfo.py
2024-05-23 08:29:16.767 [error] [Error: Command failed: C:\Users\Admin\AppData\Local\Programs\Python\Python312\python.exe -I /home/ndao/.vscode-server/extensions/ms-python.python-2024.6.0/python_files/get_output_via_markers.py /home/ndao/.vscode-server/extensions/ms-python.python-2024.6.0/python_files/interpreterInfo.py
/bin/sh: 1: C:UsersAdminAppDataLocalProgramsPythonPython312python.exe: not found

	at ChildProcess.exithandler (node:child_process:422:12)
	at ChildProcess.emit (node:events:529:35)
	at maybeClose (node:internal/child_process:1098:16)
	at Socket.<anonymous> (node:internal/child_process:450:11)
	at Socket.emit (node:events:517:28)
	at Pipe.<anonymous> (node:net:350:12)] {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312\\python.exe -I /home/ndao/.vscode-server/extensions/ms-python.python-2024.6.0/python_files/get_output_via_markers.py /home/ndao/.vscode-server/extensions/ms-python.python-2024.6.0/python_files/interpreterInfo.py'
}
2024-05-23 08:29:16.777 [info] > pyenv which python
2024-05-23 08:29:16.777 [info] cwd: .
2024-05-23 08:29:16.811 [info] Python interpreter path: /bin/python3
2024-05-23 08:29:18.216 [info] Starting Pylance language server.
